name: Compile LaTeX Document (pdflatex + biber)

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
    paths:
      - 'document/**.tex' # Only run if .tex files in 'document/' change
      - 'document/**.bib' # Or .bib files
      - '.github/workflows/latex_compile.yml' # Or if the workflow itself changes
  pull_request:
    branches:
      - main # Or your default branch
    paths:
      - 'document/**.tex'
      - 'document/**.bib'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        # Using xu-cheng/texlive-action for broader package support including biber
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full # 'full' scheme includes biber and most common packages.
                       # You could use 'basic' and specify 'packages: biber pdflatex'
                       # and any other LaTeX packages your document needs, but 'full' is safer.
          # Optional: Specify TeX Live version for cache stability
          # texlive_version: "2023"

      - name: Compile LaTeX document (pdflatex + biber)
        # We will change to the 'document' directory to run the commands
        working-directory: ./document
        run: |
          pdflatex -interaction=nonstopmode -file-line-error -shell-escape paper.tex
          biber paper # Note: biber usually takes the basename of the .tex file
          pdflatex -interaction=nonstopmode -file-line-error -shell-escape paper.tex
          pdflatex -interaction=nonstopmode -file-line-error -shell-escape paper.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf # Name of the artifact bundle
          path: document/paper.pdf # Path to the generated PDF file
          if-no-files-found: error # Fail the workflow if PDF is not found